name: mlb_test1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  intl:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - fonts/

  fonts:
     - family: Stratos
       fonts:
          - asset: fonts/stratos/Medium.ttf
          - weight: 500
          - asset: fonts/stratos/Regular.ttf
          - weight: 400

